### PR TITLE
[RFC] Include pre-generated libs/dhparams.c

### PR DESCRIPTION
**Pull request by cotequeiroz**
Hi

I've opened a PR in openwrt (https://github.com/openwrt/packages/pull/6192, CC: @yousong), because we're (hopefully to be honest) in transition from openssl 1.0 to openssl 1.1.  We are cross-compiling, and there are people compiling openssl-1.0, while others use openssl-1.1.  To further complicate matters, the host package being used (because of compatibility issues between openssl and OSX) is libressl.

My problem lies with `dhparams.c`.  I see that during build, it is generated from the `dh*.pem` files.
In my case, it uses the libressl util, which produces code that's only compatible with openssl 1.0 API.

What I have suggested there was to use a pre-generated C source that's compatible with either openssl version and libressl.

The file was generated with openssl 1.1 and a simplified inline version of DH_set0_pqg was used for openssl 1.0 and libressl compatibility.

We welcome your thoughts about the implications of doing that--or any other ideas that would be useful.  @yousong is specially concern with any security implications.  I don't see any, since the code is pretty straightforward, and you have more control over what's being actually used than "outsourcing" it.

Of course, if this is useful to more people, you can always merge this.  In that case, I thought about adding an option to configure.ac that would `touch` the `*.pem` files, in order to force the generation of a new file, so you could please both worlds.  If so, let me know and I will add a new commit.

Cheers

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by blp** [comment]
@cotequeiroz I think that it's reasonable to merge this if you fix the build errors:

```
$ make -j10
make  all-recursive
make[1]: Entering directory '/home/blp/nicira/ovs2/_build'
Making all in datapath
make[2]: Entering directory '/home/blp/nicira/ovs2/_build/datapath'
make[3]: Entering directory '/home/blp/nicira/ovs2/_build/datapath'
make[3]: Leaving directory '/home/blp/nicira/ovs2/_build/datapath'
make[2]: Leaving directory '/home/blp/nicira/ovs2/_build/datapath'
make[2]: Entering directory '/home/blp/nicira/ovs2/_build'
  GEN      utilities/ovs-lib
lib/dhparams.c
make[3]: Entering directory '/home/blp/nicira/ovs2/_build/datapath'
See above for list of violations of the rule that
every C source file must #include <config.h>.
Makefile:6229: recipe for target 'config-h-check' failed
make[2]: *** [config-h-check] Error 1
make[2]: *** Waiting for unfinished jobs....
make[3]: 'distfiles' is up to date.
make[3]: Leaving directory '/home/blp/nicira/ovs2/_build/datapath'
The following files are in git but not the distribution:
lib/dhparams.c
Makefile:6200: recipe for target 'dist-hook-git' failed
make[2]: *** [dist-hook-git] Error 1
make[2]: Leaving directory '/home/blp/nicira/ovs2/_build'
Makefile:5643: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/blp/nicira/ovs2/_build'
Makefile:3298: recipe for target 'all' failed
make: *** [all] Error 2
```

> Of course, if this is useful to more people, you can always merge this. In that case, I thought about adding an option to configure.ac that would touch the *.pem files, in order to force the generation of a new file, so you could please both worlds. If so, let me know and I will add a new commit.

I've found in the past that distributing and checking in automatically generated files isn't a good way to do things.  Thus, if necessary, I think it would be better to add a target that someone could explicitly invoke to regenerate the file rather than doing it based on dependencies.

**Comment by cotequeiroz** [comment]
I've added another commit.  See if I got exactly what you meant.  

I've added a phony `generate-dhparams-c` target to `lib/automake.mk`.  Now, where is the proper place to document that?

**Comment by blp** [comment]
Thanks for the updates.

I hacked on this a bit and posted the version that I came up with to the ovs-dev mailing list for review: https://mail.openvswitch.org/pipermail/ovs-dev/2018-June/347930.html.  It's also in patchwork: https://patchwork.ozlabs.org/patch/925658/.  What do you think?

Thanks,

Ben.

**Comment by cotequeiroz** [comment]
Looks good.  Thanks for you help.
Cheers

**Comment by blp** [comment]
I applied this to master.

**Pull request closed without merging**
