### PR TITLE
Generating windows artifacts.

### PR DESCRIPTION
**Pull request by lygstate**
# Conflicts:
#	appveyor.yml

### CODE REVIEW

**Comment by blp** [comment]
We're going to need commit messages and a Signed-off-by for these.

**Comment by aserdean** [comment]
/LGTM

@lygstate can you please include a `Signed-off-by` line in the commit message as per: http://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/#tags

The reason we ask for it can be found here:
http://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/#developer-s-certificate-of-origin

**Comment by aserdean** [comment]
Thanks for adding the sign off, however this commit: https://github.com/openvswitch/ovs/pull/303/commits/ba456b00c383a4450408f0c5723abea194c9dedc is still missing a sign off.

**Comment by aserdean** [comment]
Since this PR is stale, I sent an updated version which bundles the MSI here: https://patchwork.ozlabs.org/project/openvswitch/patch/20200824161129.620-1-aserdean@cloudbasesolutions.com/ .

**Pull request closed without merging**
