### PR TITLE
ovn-nbctl:add db commands help

### PR DESCRIPTION
**Pull request by Grim-lock**
Signed-off-by: l0310 <liw@dtdream.com>

### CODE REVIEW

**Comment by russellb** [comment]
Can you update the man page, as well?

Thanks!

**Comment by Grim-lock** [comment]
I finished according to your idea, but there is a place not good.
In db-ctl-base.man, it uses a var instead of command which to be man,  e.g. command within the same \fB\*(PN\fR invocation. I just write ovn-nbctl in db-ctl-base.xml, it does not change, if ovn-sbctl include him.
How can I do this in db-ctl-base.xml?

**Comment by russellb** [comment]
I see.  I'm not sure the best way to handle that.  I know we could come up with something, but the easiest thing is to just remove it.  It doesn't seem to harm the content to replace "<code>ovn-nbctl</code>" with "command", except the last case which would be "the command".  That's my suggestion unless someone else feels strongly that we need to continue to refer to the command by name in this part of the docs.

**Comment by blp** [comment]
It's probably fine in many individual cases to refer to the command generically.

We might want to invent a mechanism for cases where we do want to do substitutions, but we should be able to get along without it for some time.

**Comment by blp** [comment]
Grim-lock: Would you mind updating this to resolve the conflicts that have arisen since it was posted?

**Comment by russellb** [comment]
and please leave a comment on here if you post an updated patch, as github seems to only email me on comments, not when patches are updated :-/

**Comment by blp** [comment]
Grim-lock, are you abandoning this?

**Comment by Grim-lock** [comment]
Sorry for delay, I will resolve the conflicts as quickly as possible.

**Comment by Grim-lock** [comment]
Conflicts has been resolved, pls check, :)

**Comment by russellb** [comment]
Thanks @Grim-lock, I will review this today.

**Comment by russellb** [comment]
Thanks for the patch! I pushed this to master with the following changes:

1) Updated lib/automake.mk so that the build would succeed.
2) Stripped windows line endings from lib/db-ctl-base.xml

**Pull request closed without merging**
