### PR TITLE
vswitchd: Add serial number configuration.

### PR DESCRIPTION
**Pull request by KIrill-ka**
There was no way to initialize the serial number in ofproto.c.
Added it as a configuration parameter "dp-sn"

### CODE REVIEW

**Comment by KIrill-ka** [comment]
It seems that continuous-integration/travis-ci/pr failure is not related to my changes.

**Comment by blp** [comment]
Please document your new feature in NEWS and vswitchd/vswitch.xml.

**Comment by KIrill-ka** [comment]
> Please document your new feature in NEWS and vswitchd/vswitch.xml.

Done. For the serial number I added some references to the OF specification. Those are also relevant to dp-desc... Would you like me to update the documentation for dp-desc?

**Comment by blp** [comment]
> > Please document your new feature in NEWS and vswitchd/vswitch.xml.
> 
> Done. For the serial number I added some references to the OF specification. 

Thanks. It is very detailed.

> Those are also relevant to dp-desc... Would you like me to update the documentation for dp-desc?

That would be helpful, thanks.

**Comment by KIrill-ka** [comment]
Would you consider merging my changes into the master?

**Comment by blp** [comment]
I applied this to master.

**Comment by KIrill-ka** [comment]
Thanks!

**Pull request closed without merging**
