### PR TITLE
ovn: improve OVN tutorial.

### PR DESCRIPTION
**Pull request by nickcooper-zhangtonghao**
Improve the tutorial of the basic OVN features. Update the contents of
the "Locally attached networks" and "Locally attached networks with VLANs"
in detail. The logical ports of type "l2gateway" is described.

Signed-off-by: nickcooper-zhangtonghao <nickcooper-zhangtonghao@opencloud.tech>

### CODE REVIEW

**Comment by russellb** [comment]
Thanks for the patch.

The patch introduces some trailing whitespace in OVN-Tutorial.md.  Can you remove that?

env8/setup.sh includes:

`ovn-nbctl lsp-set-options sw0-port3 l2gateway-chassis=56b18105-5706-46ef-80c4-ff20979ab068 network_name=physnet1`

That UUID will be different each time the sandbox is used.  It should dynamically figure out the chassis UUID, instead.

The updates to the localnet sections are good.  A further improvement would be to simplify these, because a separate lswitch per port connected to the network is no logner required.  A single lswitch with a localnet port and N other regular ports is fine.

Finally, I would update the new section clarifying the major difference between localnet and l2gateway ports.

**Comment by nickcooper-zhangtonghao** [comment]
Thanks.
Some trailing whitespace has been removed in OVN-Tutorial.

env8/setup.sh includes:
ovn-nbctl lsp-set-options sw0-port3 l2gateway-chassis=56b18105-5706-46ef-80c4-ff20979ab068 network_name=physnet1

That UUID will be always the same, because the sandbox assigns the same UUID to this chassis via
"ovs-vsctl set open . external-ids:system-id=56b18105-5706-46ef-80c4-ff20979ab068".

**Comment by russellb** [comment]
I would squash the 2 commits into 1, but I can do that locally before pushing.

**Comment by russellb** [comment]
I made the following tweaks and applied this to master.  Thanks!

`diff --git a/tutorial/OVN-Tutorial.md b/tutorial/OVN-Tutorial.md
index 5c67b2e..a1fff0b 100644
--- a/tutorial/OVN-Tutorial.md
+++ b/tutorial/OVN-Tutorial.md
@@ -957,7 +957,10 @@ hypervisors. Please see the tutorial 3 above.
 ------------------
 
 L2Gateway provides a way to connect logical switch ports of type `l2gateway` to
-a physical network.
+a physical network.  The difference between `l2gateway` ports and `localnet` ports
+is that an `l2gateway` port is bound to a specific chassis.  A single chassis
+serves as the L2 gateway to the physical network and all traffic between
+chassis continues to go over geneve tunnels.
 
 Start with a simple logical switch with 3 logical ports.
 
diff --git a/tutorial/ovn/env8/setup.sh b/tutorial/ovn/env8/setup.sh
index d2b406c..2bb05ff 100755
--- a/tutorial/ovn/env8/setup.sh
+++ b/tutorial/ovn/env8/setup.sh
@@ -40,6 +40,7 @@ ovs-vsctl add-port br-int lport2 -- set Interface lport2 external_ids:iface-id=s
 ovn-nbctl lsp-add sw0 sw0-port3
 ovn-nbctl lsp-set-addresses sw0-port3 unknown
 ovn-nbctl lsp-set-type sw0-port3 l2gateway
+# The chassis UUID is hard-coded in tutorial/ovs-sandbox.
 ovn-nbctl lsp-set-options sw0-port3 l2gateway-chassis=56b18105-5706-46ef-80c4-ff20979ab068 network_name=physnet1
 
 ovs-vsctl --may-exist add-br br-eth1
`

**Pull request closed without merging**
