### PR TITLE
ovn/utilities: add info level log function

### PR DESCRIPTION
**Pull request by greenpau**
There is no INFO level log function. It is either ERROR or
FATAL. This PR adds it.

Signed-off-by: Paul Greenberg <greenpau@outlook.com>

### CODE REVIEW

**Comment by greenpau** [comment]
@blp , I don’t think that the test failed due to an issue in this PR. I think the failure is unrelated. Could you please take a look.

**Comment by blp** [comment]
I posted this to the ovs-dev mailing list to ensure that it gets noticed by the right people to review it (probably Guru; not me): https://patchwork.ozlabs.org/patch/906419/

**Comment by greenpau** [comment]
> I posted this to the ovs-dev mailing list to ensure that it gets noticed by the right people to review it (probably Guru; not me): https://patchwork.ozlabs.org/patch/906419/

@blp, thank you! Btw, I am working on modifying the https://github.com/openvswitch/ovs/blob/master/ovn/utilities/ovn-docker-overlay-driver.in. Currently, the code does not have any debugging or logging functionality, e.g. logging Docker requests to the plugin, etc. That's why I added the two functions. I will have a separate PR for that.

**Comment by greenpau** [comment]
@blp , closing this one in favor of https://github.com/openvswitch/ovs/pull/230

**Pull request closed without merging**
