### PR TITLE
Implement IPv6 support to ovs-docker

### PR DESCRIPTION
**Pull request by mateusvtt**

### CODE REVIEW

**Comment by shettyg** [comment]
Please add a "Signed-off-by" to the commit. Your Signed-off-by name and Author name should be the same. More details on the meaning of Signed-off-by is here (specifically in the section Developer’s Certificate of Origin):
http://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/

**Comment by shettyg** [comment]
@mateusvtt 

Sorry it took so long. You likely did a force push and I did not get a github notification that you responded to my request. The 2 commits that this pull request has makes it a little confusing. I intend to squash it.

So, would it be okay if the commit has:

Author: Mateus Tanure <mateus.tanure@pop-es.rnp.br>
Signed-off-by: Mateus Tanure <mateus.tanure@pop-es.rnp.br>

**Comment by gaby** [comment]
@mateusvtt Can you update your PR ? The work you did adding support for IPv6 is essential for ovs-docker!

**Comment by mateusvtt** [comment]
Hey, @gaby I got surprised when I received the notification, I didn't remember this PR.
I've fixed the commits mess but I don't have the context I had before to make sure everything is working, could you validate it? (CI tests seem fine) 
I had used my fork as part of a personal project and IPV6 worked well at the time. Glad to know it still might be useful.

**Comment by stathiskaps** [comment]
Hello, are there any updates on this?

**Comment by horms** [comment]
Hi,

Thanks for your contribution.

I am closing this PR as it appears to have gone stale.

If you believe this change is still relevant then please do feel welcome to resubmit it using the preferred mechanism of the Open vSwitch project, the email workflow described in [Submitting Patches](https://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/).

**Pull request closed without merging**
