### PR TITLE
bond: Fix slb-balance heuristic calculations.

### PR DESCRIPTION
**Pull request by gasmith-nutanix**
The choose_entry_to_migrate() helper tries to determine whether moving a single
MAC hash from one bond slave to another would make a tangible improvement in
balance. The crucial comparison is a delta in the ratios of tx load between
bond slaves: if the delta is greater than a threshold, the move is recommended.

It is important that both ratios are greater than (or less than) 1 for this
delta to make sense; otherwise, a very heavy MAC hash could ping-pong between
bond slaves at every rebalance interval.

### CODE REVIEW

**Comment by azhou-nicira** [comment]
Thanks for reporting the issue and working on it.

I believe the first hunk should have been covered by the list_is_short() check above.

The second hunk looks correct. But it makes the logic harder to understand. I believe
this is due to original logic being more complicated than necessary. I proposed the following
patch trying to simplify:

http://openvswitch.org/pipermail/dev/2015-September/060076.html

It should also address the bug you found. Do you mind testing it in your environment?

**Comment by gasmith-nutanix** [comment]
I prefer your proposal to mine. I'll run some tests and get back to you.

Thanks,
Greg

From: Andy Zhou
Reply-To: openvswitch/ovs
Date: Tuesday, September 15, 2015 at 2:22 PM
To: openvswitch/ovs
Cc: Greg Smith
Subject: Re: [ovs] bond: Fix slb-balance heuristic calculations. (#71)


Thanks for reporting the issue and working on it.

I believe the first hunk should have been covered by the list_is_short() check above.

The second hunk looks correct. But it makes the logic harder to understand. I believe
this is due to original logic being more complicated than necessary. I proposed the following
patch trying to simplify:

http://openvswitch.org/pipermail/dev/2015-September/060076.html

It should also address the bug you found. Do you mind testing it in your environment?

**Comment by azhou-nicira** [comment]
Thanks for reporting the issue and working on it.

I believe the first hunk should have been covered by the list_is_short()
check above.

The second hunk looks correct. But it makes the logic harder to understand.
I believe
this is due to original logic being more complicated than necessary. I
proposed the following
patch trying to simplify:

http://openvswitch.org/pipermail/dev/2015-September/060076.html

It should also address the bug you found. Do you mind testing it in your
environment?

**Comment by gasmith-nutanix** [comment]
Tried out the patch, and it looks like everything is working as expected. Thanks again for the fix!

**Comment by azhou-nicira** [comment]
Thanks for testing it.  I will wait for Ben to get chance to look at it
before committing it to master and then back port it some older branches.

**Comment by blp** [comment]
It looks like the issue that this addresses was fixed with commit c460a6a7bc751 (ofproto/bond: simplify rebalancing logic), so I'm closing it.  If I misunderstand, please reopen it or submit a new patch.

**Pull request closed without merging**
