### PR TITLE
Added pkg-config for libovn

### PR DESCRIPTION
**Pull request by hirokiht**
Added pkg-config support for libovn and the corresponding modifications

### CODE REVIEW

**Comment by blp** [comment]
Thanks for contributing to OVN!  We will need a Signed-off-by for this series.  The FAQ says the following:

Q: What's a Signed-off-by and how do I provide one?

    A: Free and open source software projects usually require a contributor to provide some assurance that they're entitled to contribute the code that they provide. Some projects, for example, do this with a Contributor License Agreement (CLA) or a copyright assignment that is signed on paper or electronically.

    For this purpose, Open vSwitch has adopted something called the Developer's Certificate of Origin (DCO), which is also used by the Linux kernel and originated there. Informally stated, agreeing to the DCO is the developer's way of attesting that a particular commit that they are contributing is one that they are allowed to contribute. You should visit https://developercertificate.org/ to read the full statement of the DCO, which is less than 200 words long.

    To certify compliance with the Developer's Certificate of Origin for a particular commit, just add the following line to the end of your commit message, properly substituting your name and email address:

        Signed-off-by: Firstname Lastname <email@example.org>

    Git has special support for adding a Signed-off-by line to a commit message: when you run "git commit", just add the -s option, as in "git commit -s". If you use the "git citool" GUI for commits, you can add a Signed-off-by line to the commit message by pressing Control+S. Other Git user interfaces may provide similar support.

**Comment by hirokiht** [comment]
Thanks for your assistance, I have added the Signed-off in my commit.

**Comment by blp** [comment]
@hirokiht Thanks for the signed-off-by.  I squashed these together and sent them to the ovs-dev mailingn list for further review: https://mail.openvswitch.org/pipermail/ovs-dev/2019-January/355509.html

**Comment by horms** [comment]
Hi,

Thanks for your contribution.

I am closing this PR as it appears to have gone stale.

If you believe this change is still relevant then please do feel welcome to resubmit it using the preferred mechanism of the OVN project, the email workflow described in [Submitting Patches](https://docs.ovn.org/en/latest/internals/contributing/submitting-patches.html).

**Pull request closed without merging**
