### PR TITLE
Fixed minor layout issue in FAQ

### PR DESCRIPTION
**Pull request by niobos**

### CODE REVIEW

**Comment by blp** [comment]
Hi, can you give us a Signed-off-by line?  CONTRIBUTING.md talks about the syntax and the meaning of this line.

**Comment by blp** [comment]
Closing after no response from poster in months.

**Comment by nielslaukens** [comment]
This licensing thing is really going to far... The proposed patch literally does not contain any (new) text at all, let alone something that is considerable under copyright law as a "creative work".

**Comment by niobos** [comment]
This licensing thing is really going to far... The proposed patch literally does not contain any (new) text at all, let alone something that is considerable under copyright law as a "creative work".

**Pull request closed without merging**
