### PR TITLE
removed "shadow" warnings while compiling with clang by preventing re…

### PR DESCRIPTION
**Pull request by damijans**
…cursively call __bswap_xx() function.

### CODE REVIEW

**Comment by blp** [comment]
Thanks for the fix.

Can you give an example of the warnings that this fixes?

**Comment by damijans** [comment]
Hi,

I am using clang version 3.8.0-2ubuntu4. When I did a clean rebuild, compiler reported with 1750 warnings of the following type:

....
./include/openvswitch/nsh.h:347:92: warning: declaration shadows a local variable [-Wshadow]
    return (__extension__ ({ unsigned int __v, __x = (((__extension__ ({ unsigned int __v, __x = (path_hdr); if (__builtin_constant_p (__x)) __v = ((((__x) & 0xff000000) >> 24) | (((__x) & 0x00ff0000) >> 8) | (((__x) & 0x0000ff00) << 8) | (((__x) & 0x000000ff) << 24)); else __asm__ ("bswap %0" : "=r" (__v) : "0" (__x)); __v; })) & 0xffffff00) >> 8); if (__builtin_constant_p (__x)) __v = ((((__x) & 0xff000000) >> 24) | (((__x) & 0x00ff0000) >> 8) | (((__x) & 0x0000ff00) << 8) | (((__x) & 0x000000ff) << 24)); else __asm__ ("bswap %0" : "=r" (__v) : "0" (__x)); __v; }));
                                                                                           ^
./include/openvswitch/nsh.h:347:48: note: previous declaration is here
    return (__extension__ ({ unsigned int __v, __x = (((__extension__ ({ unsigned int __v, __x = (path_hdr); if (__builtin_constant_p (__x)) __v = ((((__x) & 0xff000000) >> 24) | (((__x) & 0x00ff0000) >> 8) | (((__x) & 0x0000ff00) << 8) | (((__x) & 0x000000ff) << 24)); else __asm__ ("bswap %0" : "=r" (__v) : "0" (__x)); __v; })) & 0xffffff00) >> 8); if (__builtin_constant_p (__x)) __v = ((((__x) & 0xff000000) >> 24) | (((__x) & 0x00ff0000) >> 8) | (((__x) & 0x0000ff00) << 8) | (((__x) & 0x000000ff) << 24)); else __asm__ ("bswap %0" : "=r" (__v) : "0" (__x)); __v; }));
.....
                                               ^
In most cases compiler complains about inline functions implemented in nsh.h. The problem was in calling htonXXX() (outer function) where apparent functions ntohYYY() (inner function) are called as a function argument. Both of these two functions are actually macros which by calling bswap() functions instantiate variables with the same name __v and here the instantiation of outer variable (from example the one which was instantiate in htonXXX()) shadows the inner variable (the one which was called from ntohYYY() function. 

This type of warning can gracefully be avoiding by calling first calling the "inner" function, remember its result on a stack and calling the "outer" function afterwards and passing the stack variable.

Note this change is just a cosmetic one, there is nothing wrong with the source code, you warnings are removed. Note also that because the change is made in inline functions this small change has a huge effect since most of aforementioned 1750 warnings disappear.  

I am attaching results of clean rebuild before and after the change.

[clang.compile.before.txt](https://github.com/openvswitch/ovs/files/3171648/clang.compile.before.txt)
[clang.compile.after.txt](https://github.com/openvswitch/ovs/files/3171647/clang.compile.after.txt)

**Comment by damijans** [comment]
Hi,
I don't know you've been informed, I have updated pull request with
additional information.
br, damijan

V V pet., 10. maj 2019 ob 15:43 je oseba Ben Pfaff <notifications@github.com>
napisala:

**Comment by blp** [comment]
Thank you. I applied this to the master branch.

**Pull request closed without merging**
